---
- name: Add group superusers, add user2 and user3
  hosts: tag_Name_Ubuntu_Server_1
  gather_facts: no
  become: yes

  tasks:
    - name: Create group "superusers"
      group:
        name: superusers
        state: present

    - name: Add the user2 and user3 to the superusers group
      user:
        name: "{{ item }}"
        group: superusers
        state: present
      with_items:
        - user2
        - user3

    - name: Validate the sudoers file before saving
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%superusers ALL='
        line: '%superusers ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
