---
# tasks file for docker_redhat
- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - ca-certificates
    - curl
    - python3-pip
    - python3-setuptools

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum: name=docker-ce state=latest update_cache=yes

- name: Start docker
  service: name=docker state=started enabled=yes
