---
# tasks file for php
- name: Install PHP packages
  apt: name="{{ item }}" state=latest update_cache=yes
  loop: ["php7.4", "php7.4-fpm"]

- name: Start PHP-FPM
  service: name=php7.4-fpm state=started enabled=yes

- name: Setting up php-fpm configuration
  template: src=www.conf.j2 dest=/etc/php/7.4/fpm/pool.d/www.conf
  notify: Restart PHP-FPM
